In [72]:
import pandas as pd

In [73]:
#read the csv file for well data part1
welldata01_df = pd.read_csv("data/part1_1982-2017.csv")
welldata01_df.head()

,API/UWI,Operator Alias,Well/Lease Name,Well Number,Reservoir,Production Type,Producing Status,Drill Type,First Prod Date,Last Prod Date,Cum Gas,Cum Oil,Cum BOE,Daily Gas,Daily Oil,First Month Oil,First Month Gas,First 6 Oil,First 6 Gas,First 6 BOE,First 12 Oil,First 12 Gas,First 12 BOE,Last Test Date,Last Flow Pressure,Peak Gas,Peak Oil,Peak BOE,Upper Perforation,Lower Perforation,Gas Gravity,Oil Gravity,Completion Date,Well Count,Max Active Wells,Months Produced,Lease Number,Spud Date,Measured Depth (TD),True Vertical Depth,Perforated Interval Length,Field,Section,Block,Surface Latitude (WGS84),Surface Longitude (WGS84)
0,42301331730000,"ANADARKO E&P ONSHORE, LLC",SAVAGE 54-2-22 UNIT,1H,WOLFCAMP,OIL,ACTIVE,H,7/1/2017,7/1/2017,22456.0,5549.0,9292,724.0,179.0,5549.0,22456.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22456.0,5549.0,9292,NaN,NaN,NaN,NaN,NaN,1,1,1,P821799,3/27/2017,12100,NaN,NaN,PHANTOM,NaN,NaN,31.826158,-103.643763
1,42301333080000,MEWBOURNE HOLDINGS INC,ZUMA 3 57-T1-3X10,W102AP,WOLFCAMP,OIL,ACTIVE,H,7/1/2017,7/1/2017,72.0,547.0,559,2.0,18.0,547.0,72.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.0,547.0,559,NaN,NaN,NaN,NaN,NaN,1,1,1,P824905,5/8/2017,20470,NaN,NaN,PHANTOM,NaN,NaN,31.999605,-103.941079
2,42301332080000,EOG RESOURCES INCORPORATED,LINK VJ RANCH 23-11B,2H,WOLFCAMP,OIL,ACTIVE,H,7/1/2017,7/1/2017,74305.0,21234.0,33618,2397.0,685.0,21234.0,74305.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74305.0,21234.0,33618,NaN,NaN,NaN,NaN,NaN,1,1,1,P822617,4/8/2017,14000,NaN,NaN,PHANTOM,NaN,NaN,31.838967,-103.735467
3,42301330570000,DEVON ENERGY CORPORATION,BOYD 11 101H,101H,WOLFCAMP,OIL,ACTIVE,H,5/1/2017,6/1/2017,40193.0,19652.0,26351,659.0,322.0,2156.0,5898.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34295.0,17496.0,23212,NaN,NaN,NaN,NaN,NaN,1,1,2,P819526,1/22/2017,17570,NaN,NaN,PHANTOM,NaN,NaN,31.943227,-103.354456
4,42301330560000,MEWBOURNE HOLDINGS INC,TXL 19,H301DM,BONE SPRING,OIL,ACTIVE,H,7/1/2017,7/1/2017,43538.0,15861.0,23117,1404.0,512.0,15861.0,43538.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43538.0,15861.0,23117,NaN,NaN,NaN,NaN,NaN,1,1,1,P819476,4/24/2017,14375,NaN,NaN,SANDBAR,NaN,NaN,31.955776,-103.905377

In [74]:
#list all the header column 
list(welldata01_df)

['API/UWI',
 'Operator Alias',
 'Well/Lease Name',
 'Well Number',
 'Reservoir',
 'Production Type',
 'Producing Status',
 'Drill Type',
 'First Prod Date',
 'Last Prod Date',
 'Cum Gas',
 'Cum Oil',
 'Cum BOE',
 'Daily Gas',
 'Daily Oil',
 'First Month Oil',
 'First Month Gas',
 'First 6 Oil',
 'First 6 Gas',
 'First 6 BOE',
 'First 12 Oil',
 'First 12 Gas',
 'First 12 BOE',
 'Last Test Date',
 'Last Flow Pressure',
 'Peak Gas',
 'Peak Oil',
 'Peak BOE',
 'Upper Perforation',
 'Lower Perforation',
 'Gas Gravity',
 'Oil Gravity',
 'Completion Date',
 'Well Count',
 'Max Active Wells',
 'Months Produced',
 'Lease Number',
 'Spud Date',
 'Measured Depth (TD)',
 'True Vertical Depth',
 'Perforated Interval Length',
 'Field',
 'Section',
 'Block',
 'Surface Latitude (WGS84)',
 'Surface Longitude (WGS84)']

In [76]:
# renamer the columns header
welldata01_df.rename(columns={
 'API/UWI':'API',
 'Operator Alias': 'Operator',
 'Well/Lease Name':'Lease_Name',
 'Well Number':'Well_Number',
 'Production Type': 'Production_type',
 'Producing Status':'Production_Status',
 'Drill Type':'Drilling_Type',
 'First Prod Date':'First_Peoduction_Day',
 'Last Prod Date': 'Last_Production_Date',
 'Cum Gas':'Cum_Gas',
 'Cum Oil':'Cum_Oil',
 'Cum BOE':'Cum_BOE',
 'Daily Gas':'Daily_Gas',
 'Daily Oil':'Daily_Oil',
 'First Month Oil':'First_Month_Oil',
 'First Month Gas':'First_Month_Gas',
 'First 6 Oil':'First_6_Oil',
 'First 6 Gas':'First_6_Gas',
 'First 6 BOE':'First_6_BOE,
 'First 12 Oil':'First_12_Oil',
 'First 12 Gas':'First 12 Gas',
 'First 12 BOE':'First 12 BOE',
 'Last Test Date':'Last Test Date',
 'Last Flow Pressure':'Last Test Date',
 'Peak Gas',
 'Peak Oil',
 'Peak BOE',
 'Upper Perforation',
 'Lower Perforation',
 'Gas Gravity',
 'Oil Gravity',
 'Completion Date',
 'Well Count',
 'Max Active Wells',
 'Months Produced',
 'Lease Number',
 'Spud Date',
 'Measured Depth (TD)',
 'True Vertical Depth',
 'Perforated Interval Length',
 'Field',
 'Section',
 'Block',
 'Surface Latitude (WGS84)',
 'Surface Longitude (WGS84)']}, inplace=True)

In [77]:
welldata01_df.head()

,API,Operator,Lease_Name,Well_Number,Reservoir,Production_type,Production_Status,Drilling_Type,First_Peoduction_Day,Last_Production_Date,Cum_Gas,Cum Oil,Cum BOE,Daily Gas,Daily Oil,First Month Oil,First Month Gas,First 6 Oil,First 6 Gas,First 6 BOE,First 12 Oil,First 12 Gas,First 12 BOE,Last Test Date,Last Flow Pressure,Peak Gas,Peak Oil,Peak BOE,Upper Perforation,Lower Perforation,Gas Gravity,Oil Gravity,Completion Date,Well Count,Max Active Wells,Months Produced,Lease Number,Spud Date,Measured Depth (TD),True Vertical Depth,Perforated Interval Length,Field,Section,Block,Surface Latitude (WGS84),Surface Longitude (WGS84)
0,42301331730000,"ANADARKO E&P ONSHORE, LLC",SAVAGE 54-2-22 UNIT,1H,WOLFCAMP,OIL,ACTIVE,H,7/1/2017,7/1/2017,22456.0,5549.0,9292,724.0,179.0,5549.0,22456.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22456.0,5549.0,9292,NaN,NaN,NaN,NaN,NaN,1,1,1,P821799,3/27/2017,12100,NaN,NaN,PHANTOM,NaN,NaN,31.826158,-103.643763
1,42301333080000,MEWBOURNE HOLDINGS INC,ZUMA 3 57-T1-3X10,W102AP,WOLFCAMP,OIL,ACTIVE,H,7/1/2017,7/1/2017,72.0,547.0,559,2.0,18.0,547.0,72.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.0,547.0,559,NaN,NaN,NaN,NaN,NaN,1,1,1,P824905,5/8/2017,20470,NaN,NaN,PHANTOM,NaN,NaN,31.999605,-103.941079
2,42301332080000,EOG RESOURCES INCORPORATED,LINK VJ RANCH 23-11B,2H,WOLFCAMP,OIL,ACTIVE,H,7/1/2017,7/1/2017,74305.0,21234.0,33618,2397.0,685.0,21234.0,74305.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74305.0,21234.0,33618,NaN,NaN,NaN,NaN,NaN,1,1,1,P822617,4/8/2017,14000,NaN,NaN,PHANTOM,NaN,NaN,31.838967,-103.735467
3,42301330570000,DEVON ENERGY CORPORATION,BOYD 11 101H,101H,WOLFCAMP,OIL,ACTIVE,H,5/1/2017,6/1/2017,40193.0,19652.0,26351,659.0,322.0,2156.0,5898.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34295.0,17496.0,23212,NaN,NaN,NaN,NaN,NaN,1,1,2,P819526,1/22/2017,17570,NaN,NaN,PHANTOM,NaN,NaN,31.943227,-103.354456
4,42301330560000,MEWBOURNE HOLDINGS INC,TXL 19,H301DM,BONE SPRING,OIL,ACTIVE,H,7/1/2017,7/1/2017,43538.0,15861.0,23117,1404.0,512.0,15861.0,43538.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43538.0,15861.0,23117,NaN,NaN,NaN,NaN,NaN,1,1,1,P819476,4/24/2017,14375,NaN,NaN,SANDBAR,NaN,NaN,31.955776,-103.905377